repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    exclude: "mkdocs.yml"
  - id: end-of-file-fixer
    exclude: ".*.svg"
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer
  - id: detect-private-key
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.146
  hooks:
    - id: ruff
      args: ["--fix"]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      language_version: python3.9
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/python-poetry/poetry
  rev: 1.2.2  # add version here
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
- repo: local
  hooks:
  - id: pytest
    name: pytest-check
    entry: poetry run python -m pytest -x
    language: system
    pass_filenames: false
    always_run: true
  - id: build_docs
    name: build_docs
    entry: poetry run python -m mkdocs build --strict
    language: system
    pass_filenames: false
    always_run: true
