repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
    exclude: "mkdocs.yml"
  - id: end-of-file-fixer
    exclude: ".*.svg"
  - id: trailing-whitespace
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/PyCQA/autoflake
  rev: v1.7.7
  hooks:
  - id: autoflake
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.100
  hooks:
    - id: ruff
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      language_version: python3.9
- repo: https://github.com/python-poetry/poetry
  rev: 1.2.2  # add version here
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort .
    language: system
    always_run: true
    pass_filenames: false
  - id: pytest
    name: pytest-check
    entry: poetry run python -m pytest -x
    language: system
    pass_filenames: false
    always_run: true
  - id: build_nbs
    name: build_nbs
    entry: bash docs/render_nbs.bash
    language: system
    pass_filenames: false
    always_run: true
  - id: build_docs
    name: build_docs
    entry: poetry run python -m mkdocs build --strict
    language: system
    pass_filenames: false
    always_run: true
