repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
    exclude: "mkdocs.yml"
  - id: end-of-file-fixer
    exclude: ".*.svg"
  - id: trailing-whitespace
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
- repo: https://github.com/PyCQA/autoflake
  rev: v1.5.3
  hooks:
  - id: autoflake
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black .
    language: system
    always_run: true
    pass_filenames: false
  - id: isort
    name: isort
    entry: poetry run isort .
    language: system
    always_run: true
    pass_filenames: false
  - id: pydocstringformatter
    name: pydocstringformatter
    entry: poetry run pydocstringformatter elfragmentador
    language: system
    always_run: true
    include: ".*.py"
  - id: flake8
    name: flake8
    entry: poetry run flake8 elfragmentador
    language: system
    always_run: true
    pass_filenames: false
  - id: pytest
    name: pytest-check
    entry: poetry run python -m pytest -x
    language: system
    pass_filenames: false
    always_run: true
  - id: build_nbs
    name: build_nbs
    entry: bash docs/render_nbs.bash
    language: system
    pass_filenames: false
    always_run: true
  - id: build_docs
    name: build_docs
    entry: poetry run python -m mkdocs build --strict
    language: system
    pass_filenames: false
    always_run: true
