
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
      exclude: "mkdocs.yml"
    - id: end-of-file-fixer
      exclude: ".*.svg"
    - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
    -   id: autoflake
  - repo: local
    hooks:
      - id: pydocstringformatter
        name: pydocstringformatter
        entry: poetry run pydocstringformatter elfragmentador
        language: system
        always_run: true
        include: ".*.py"
      - id: flake8
        name: flake8
        entry: poetry run flake8 elfragmentador
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest-check
        entry: poetry run python -m pytest -x
        language: system
        pass_filenames: false
        always_run: true
