site_name: ElFragmentador Documentation

theme:
  name: material

extra:
  analytics:
    provider: google
    property: G-QKEQ9R2MR7


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkquartodocs:
      keep_output: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_members_full_path: true
            show_object_full_path: false
            show_category_heading: true
            docstring_style: google
            line_length: 120
            members_order: source
            show_if_no_docstring: true
            show_signature_annotations: true
            annotations_path: source
            docstring_section_style: spacy
            docstring_options:
              ignore_init_summary: no
            merge_init_into_class: yes
