stages:
  qc_rt_data:
    deps:
      - prospect_data/
      - scripts/rt_qc.py
    outs:
      - processed_data/rt_qc.parquet
    cmd:
      - poetry run python scripts/rt_qc.py
    
  make_spectra_vectors:
    foreach:
      - TUM_aspn/TUM_aspn_10_01_01
      - TUM_aspn/TUM_aspn_11_01_01
      - TUM_aspn/TUM_aspn_12_01_01
      - TUM_aspn/TUM_aspn_13_01_01
      - TUM_aspn/TUM_aspn_14_01_01
      - TUM_aspn/TUM_aspn_15_01_01
      - TUM_aspn/TUM_aspn_16_01_01
      - TUM_aspn/TUM_aspn_17_01_01
      - TUM_aspn/TUM_aspn_18_01_01
      - TUM_aspn/TUM_aspn_19_01_01
      - TUM_aspn/TUM_aspn_1_01_01
      - TUM_aspn/TUM_aspn_20_01_01
      - TUM_aspn/TUM_aspn_21_01_01
      - TUM_aspn/TUM_aspn_22_01_01
      - TUM_aspn/TUM_aspn_23_01_01
      - TUM_aspn/TUM_aspn_24_01_01
      - TUM_aspn/TUM_aspn_25_01_01
      - TUM_aspn/TUM_aspn_26_01_01
      - TUM_aspn/TUM_aspn_27_01_01
      - TUM_aspn/TUM_aspn_28_01_01
      - TUM_aspn/TUM_aspn_29_01_01
      - TUM_aspn/TUM_aspn_2_01_01
      - TUM_aspn/TUM_aspn_30_01_01
      - TUM_aspn/TUM_aspn_31_01_01
      - TUM_aspn/TUM_aspn_32_01_01
      - TUM_aspn/TUM_aspn_33_01_01
      - TUM_aspn/TUM_aspn_34_01_01
      - TUM_aspn/TUM_aspn_35_01_01
      - TUM_aspn/TUM_aspn_36_01_01
      - TUM_aspn/TUM_aspn_37_01_01
      - TUM_aspn/TUM_aspn_38_01_01
      - TUM_aspn/TUM_aspn_39_01_01
      - TUM_aspn/TUM_aspn_3_01_01
      - TUM_aspn/TUM_aspn_40_01_01
      - TUM_aspn/TUM_aspn_41_01_01
      - TUM_aspn/TUM_aspn_4_01_01
      - TUM_aspn/TUM_aspn_5_01_01
      - TUM_aspn/TUM_aspn_6_01_01
      - TUM_aspn/TUM_aspn_7_01_01
      - TUM_aspn/TUM_aspn_8_01_01
      - TUM_aspn/TUM_aspn_9_01_01
      - TUM_first_pool_1/TUM_first_pool_10_01_01
      - TUM_first_pool_1/TUM_first_pool_11_01_01
      - TUM_first_pool_1/TUM_first_pool_12_01_01
      - TUM_first_pool_1/TUM_first_pool_13_01_01
      - TUM_first_pool_1/TUM_first_pool_14_01_01
      - TUM_first_pool_1/TUM_first_pool_15_01_01
      - TUM_first_pool_1/TUM_first_pool_16_01_01
      - TUM_first_pool_1/TUM_first_pool_17_01_01
      - TUM_first_pool_1/TUM_first_pool_18_01_01
      - TUM_first_pool_1/TUM_first_pool_19_01_01
      - TUM_first_pool_1/TUM_first_pool_1_01_01
      - TUM_first_pool_1/TUM_first_pool_20_01_01
      - TUM_first_pool_1/TUM_first_pool_21_01_01
      - TUM_first_pool_1/TUM_first_pool_22_01_01
      - TUM_first_pool_1/TUM_first_pool_23_01_01
      - TUM_first_pool_1/TUM_first_pool_24_01_01
      - TUM_first_pool_1/TUM_first_pool_25_01_01
      - TUM_first_pool_1/TUM_first_pool_26_01_01
      - TUM_first_pool_1/TUM_first_pool_27_01_01
      - TUM_first_pool_1/TUM_first_pool_28_01_01
      - TUM_first_pool_1/TUM_first_pool_29_01_01
      - TUM_first_pool_1/TUM_first_pool_2_01_01
      - TUM_first_pool_1/TUM_first_pool_30_01_01
      - TUM_first_pool_1/TUM_first_pool_31_01_01
      - TUM_first_pool_1/TUM_first_pool_32_01_01
      - TUM_first_pool_1/TUM_first_pool_33_01_01
      - TUM_first_pool_1/TUM_first_pool_34_01_01
      - TUM_first_pool_1/TUM_first_pool_35_01_01
      - TUM_first_pool_1/TUM_first_pool_36_01_01
      - TUM_first_pool_1/TUM_first_pool_37_01_01
      - TUM_first_pool_1/TUM_first_pool_38_01_01
      - TUM_first_pool_1/TUM_first_pool_39_01_01
      - TUM_first_pool_1/TUM_first_pool_3_01_01
      - TUM_first_pool_1/TUM_first_pool_40_01_01
      - TUM_first_pool_1/TUM_first_pool_41_01_01
      - TUM_first_pool_1/TUM_first_pool_42_01_01
      - TUM_first_pool_1/TUM_first_pool_43_01_01
      - TUM_first_pool_1/TUM_first_pool_44_01_01
      - TUM_first_pool_1/TUM_first_pool_45_01_01
      - TUM_first_pool_1/TUM_first_pool_46_01_01
      - TUM_first_pool_1/TUM_first_pool_47_01_01
      - TUM_first_pool_1/TUM_first_pool_48_01_01
      - TUM_first_pool_1/TUM_first_pool_49_01_01
      - TUM_first_pool_1/TUM_first_pool_4_01_01
      - TUM_first_pool_1/TUM_first_pool_50_01_01
      - TUM_first_pool_1/TUM_first_pool_51_01_01
      - TUM_first_pool_1/TUM_first_pool_52_01_01
      - TUM_first_pool_1/TUM_first_pool_53_01_01
      - TUM_first_pool_1/TUM_first_pool_54_01_01
      - TUM_first_pool_1/TUM_first_pool_55_01_01
      - TUM_first_pool_1/TUM_first_pool_56_01_01
      - TUM_first_pool_1/TUM_first_pool_57_01_01
      - TUM_first_pool_1/TUM_first_pool_58_01_01
      - TUM_first_pool_1/TUM_first_pool_59_01_01
      - TUM_first_pool_1/TUM_first_pool_5_01_01
      - TUM_first_pool_1/TUM_first_pool_60_01_01
      - TUM_first_pool_1/TUM_first_pool_61_01_01
      - TUM_first_pool_1/TUM_first_pool_62_01_01
      - TUM_first_pool_1/TUM_first_pool_6_01_01
      - TUM_first_pool_1/TUM_first_pool_7_01_01
      - TUM_first_pool_1/TUM_first_pool_8_01_01
      - TUM_first_pool_1/TUM_first_pool_9_01_01
      - TUM_first_pool_2/TUM_first_pool_63_01_01
      - TUM_first_pool_2/TUM_first_pool_64_01_01
      - TUM_first_pool_2/TUM_first_pool_65_01_01
      - TUM_first_pool_2/TUM_first_pool_66_01_01
      - TUM_first_pool_2/TUM_first_pool_67_01_01
      - TUM_first_pool_2/TUM_first_pool_68_01_01
      - TUM_first_pool_2/TUM_first_pool_69_01_01
      - TUM_first_pool_2/TUM_first_pool_70_01_01
      - TUM_first_pool_2/TUM_first_pool_71_01_01
      - TUM_first_pool_2/TUM_first_pool_72_01_01
      - TUM_first_pool_2/TUM_first_pool_73_01_01
      - TUM_first_pool_2/TUM_first_pool_74_01_01
      - TUM_first_pool_2/TUM_first_pool_75_01_01
      - TUM_first_pool_2/TUM_first_pool_76_01_01
      - TUM_first_pool_2/TUM_first_pool_77_01_01
      - TUM_first_pool_2/TUM_first_pool_78_01_01
      - TUM_first_pool_2/TUM_first_pool_79_01_01
      - TUM_first_pool_2/TUM_first_pool_80_01_01
      - TUM_first_pool_2/TUM_first_pool_81_01_01
      - TUM_first_pool_2/TUM_first_pool_82_01_01
      - TUM_first_pool_2/TUM_first_pool_83_01_01
      - TUM_first_pool_2/TUM_first_pool_84_01_01
      - TUM_first_pool_2/TUM_first_pool_85_01_01
      - TUM_first_pool_2/TUM_first_pool_86_01_01
      - TUM_first_pool_2/TUM_first_pool_87_01_01
      - TUM_first_pool_2/TUM_first_pool_88_01_01
      - TUM_first_pool_2/TUM_first_pool_89_01_01
      - TUM_first_pool_2/TUM_first_pool_90_01_01
      - TUM_first_pool_2/TUM_first_pool_91_01_01
      - TUM_first_pool_2/TUM_first_pool_92_01_01
      - TUM_first_pool_2/TUM_first_pool_93_01_01
      - TUM_first_pool_2/TUM_first_pool_94_01_01
      - TUM_first_pool_2/TUM_first_pool_95_01_01
      - TUM_first_pool_2/TUM_first_pool_96_01_01
      - TUM_first_pool_2/TUM_first_pool_97_01_01
      - TUM_first_pool_2/TUM_first_pool_98_01_01
      - TUM_first_pool_3/TUM_first_pool_100_01_01
      - TUM_first_pool_3/TUM_first_pool_101_01_01
      - TUM_first_pool_3/TUM_first_pool_102_01_01
      - TUM_first_pool_3/TUM_first_pool_103_01_01
      - TUM_first_pool_3/TUM_first_pool_104_01_01
      - TUM_first_pool_3/TUM_first_pool_105_01_01
      - TUM_first_pool_3/TUM_first_pool_106_01_01
      - TUM_first_pool_3/TUM_first_pool_107_01_01
      - TUM_first_pool_3/TUM_first_pool_108_01_01
      - TUM_first_pool_3/TUM_first_pool_109_01_01
      - TUM_first_pool_3/TUM_first_pool_110_01_01
      - TUM_first_pool_3/TUM_first_pool_111_01_01
      - TUM_first_pool_3/TUM_first_pool_112_01_01
      - TUM_first_pool_3/TUM_first_pool_113_01_01
      - TUM_first_pool_3/TUM_first_pool_114_01_01
      - TUM_first_pool_3/TUM_first_pool_115_01_01
      - TUM_first_pool_3/TUM_first_pool_116_01_01
      - TUM_first_pool_3/TUM_first_pool_117_01_01
      - TUM_first_pool_3/TUM_first_pool_118_01_01
      - TUM_first_pool_3/TUM_first_pool_119_01_01
      - TUM_first_pool_3/TUM_first_pool_120_01_01
      - TUM_first_pool_3/TUM_first_pool_121_01_01
      - TUM_first_pool_3/TUM_first_pool_122_01_01
      - TUM_first_pool_3/TUM_first_pool_123_01_01
      - TUM_first_pool_3/TUM_first_pool_99_01_01
      - TUM_third_pool/TUM_third_pool_1_01_01
      - TUM_third_pool/TUM_third_pool_2_01_01
      - TUM_third_pool/TUM_third_pool_3_01_01
      - TUM_third_pool/TUM_third_pool_4_01_01
      - TUM_third_pool/TUM_third_pool_5_01_01
      - TUM_third_pool/TUM_third_pool_6_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_10_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_11_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_12_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_13_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_14_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_15_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_16_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_17_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_18_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_19_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_1_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_20_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_21_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_22_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_23_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_24_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_25_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_26_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_27_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_28_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_29_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_2_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_30_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_31_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_32_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_33_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_34_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_35_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_36_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_37_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_38_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_39_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_3_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_40_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_41_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_42_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_43_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_44_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_45_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_46_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_47_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_48_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_49_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_4_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_50_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_51_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_52_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_53_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_54_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_55_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_56_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_57_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_58_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_59_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_5_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_60_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_61_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_62_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_63_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_64_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_65_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_66_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_67_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_68_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_69_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_6_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_70_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_71_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_72_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_73_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_74_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_75_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_76_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_77_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_78_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_79_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_7_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_80_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_81_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_82_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_83_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_84_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_85_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_86_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_87_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_88_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_8_01_01
      - Thermo_SRM_Pool/Thermo_SRM_Pool_9_01_01
    do:
      cmd:
        poetry run python scripts/process_fragment_data.py \
        prospect_data/${item}_annotation.parquet \
        prospect_data_vectors/${item}_vector.parquet
      outs:
        - prospect_data_vectors/${item}_vector.parquet
      deps:
        - prospect_data/${item}_annotation.parquet 
