
name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      # Initial Setup
      - uses: actions/checkout@v3

      # Documentation setup
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: View Quarto version
        run:
          quarto --version

      # Python setup
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: View Python --version
        run: python --version

      # Poetry Setup
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: '1.2.0'
      - name: View poetry --version
        run: poetry --version

      # Package Setup
      - name: Install deps
        run: poetry install -n -v --all-extras

      # Build
      - name: Build Notebooks
        run: bash docs/render_nbs.bash
      - name: Build package
        run: |
          poetry build

      # Publishing Docs
      - name: Deploy Docs
        run: |
          poetry run python -m mkdocs gh-deploy --strict --force

      # Publish Package
      - name: Publish Setup
        env:
          PYPITOKEN: ${{ secrets.PYPITOKEN }}
        run: |
          poetry config pypi-token.pypi ${PYPITOKEN}
      - name: Publish
        run: |
          poetry publish --build --no-interaction
