
name: CI Testing
on: [pull_request, push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10]
        poetry-version: [1.1.14]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help
      - name: Install deps
        run: poetry install
      - name: Black
        run: poetry run black . --check
      - name: Pytest
        run: poetry run pytest
      - name: flake8
        run: poetry run flake8
