
name: CI Testing

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]
  schedule:
  - cron: "0 0 1 1/1 *" # Run monthly.

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.x',]
        poetry-version: ['1.1.14',]
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help
      - name: Install deps
        run: poetry install -n -vv
      - name: Black
        run: poetry run python -m black . --check --diff
      - name: flake8
        run: poetry run flake8 elfragmentador
      - name: isort
        run: poetry run isort . --check
      - name: Pytest
        run: poetry run python -m pytest
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: View Quarto version
        run:
          quarto --version
      - name: Build Notebooks
        run: bash docs/render_nbs.bash
      - name: mkdocs
        run: poetry run python -m mkdocs build --strict
